train_file: ['data/ADNI_train.json']
val_file: ['data/ADNI_val.json']
test_file: ['data/ADNI_test.json']

patch_size: 32
image_res: [128, 128, 128]
in_chans: 1
vision_width: 768
embed_dim: 256
depth: 6
num_heads: 12
batch_size: 64
temp: 0.07
mlm_probability: 0.25
queue_size: 1024
momentum: 0.995
alpha: 0.4

optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-4, epochs: 120, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 20, cooldown_epochs: 0}